# Generated by Django 5.2.14 on 2026-06-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_design_pattern_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
