# Generated by Django 5.2.14 on 2026-05-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_design_pattern_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='agency_code',
        ),
        migrations.RemoveField(
            model_name='users',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_new_user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='os_status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='state',
        ),
        migrations.RemoveField(
            model_name='users',
            name='work_phone',
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
