# Generated by Django 5.2.14 on 2026-05-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_design_pattern_app', '0002_alter_users_managers_remove_users_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
