# Generated by Django 5.2.14 on 2026-06-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_design_pattern_app', '0003_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
