# Generated by Django 5.2.14 on 2026-06-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_design_pattern_app', '0005_remove_users_full_name_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
